### ISSUE TITLE
How to GET private posts 

### ISSUE THREAD

**Issue by lorenzochaudessolle** [imranhsayed/headless-cms#11]
Hi, 
I begin to thank you for this plugin which is very easy to use !

I want to get posts from my wordpress headless on my frontend app and I want to put all my posts in private to only access them with the API and my frontend, this plugin offers the possibility to do this ?

Thanks a lot and happy good year !

**Comment by IRediTOTO** [comment]
:( is this project dead :(

**Comment by lorenzochaudessolle** [comment]
Okey thx for answer me
