### ISSUE TITLE
Warning Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by JeanPaul20** [imranhsayed/headless-cms#54]
Hey Imran, first great video tutorial about WooCommerce REST API.
I had a problem early on with `wp-json/rae/v1/header-footer?header_location_id=hcms-menu-header`. It gave me an error that there was a problem on line 139 of the plugin class file class-header-footer-api.php
Main problem was that the return image was not checked of verified, however you refer to name it.
Original code is:

`/**
	 * Get Custom logo URL.
	 *
	 * @param string $key Key.
	 *
	 * @return string Image.
	 */
	public function get_custom_logo_url( $key ) {

		$custom_logo_id = get_theme_mod( $key );
		$image          = wp_get_attachment_image_src( $custom_logo_id, 'full' );
		return $image[0];
	}`

I change the return value and it worked.

`/**
	 * Get Custom logo URL.
	 *
	 * @param string $key Key.
	 *
	 * @return string Image.
	 */
	public function get_custom_logo_url( $key ) {

		$custom_logo_id = get_theme_mod( $key );
		$image          = wp_get_attachment_image_src( $custom_logo_id, 'full' );
		if($image) return $image[0];
	}`

Not sure if it was a problem with my WordPress setup or something else, but after the change the API called worked, and I could read the values.
Before I only got an error message.
Works for me now, just wanted to share this with you.
Take care
Jean Paul

**Comment by imranhsayed** [comment]
Thanks. Glad to know its resolved.
